loginWebService = "http://127.0.0.1:5173/api/login"
clientWebService = "http://127.0.0.1:5173/api/login"
tibiaPageUrl = "http://127.0.0.1:5173/"
tibiaStoreGetCoinsUrl = "http://127.0.0.1:5173/shop/coins"
getPremiumUrl = "http://127.0.0.1:5173/pages/vip-features"
createAccountUrl = "http://127.0.0.1:5173/account/signup"
accessAccountUrl = "http://127.0.0.1:5173/account"
lostAccountUrl = "http://127.0.0.1:5173/account/lost"
manualUrl = "http://127.0.0.1:5173/pages/server-info"
faqUrl = "http://127.0.0.1:5173/pages/server-info"
premiumFeaturesUrl = "http://127.0.0.1:5173/pages/vip-features"
crashReportUrl = "http://127.0.0.1:5173/api/crash-report"
cipSoftUrl = "http://127.0.0.1:5173/"
fpsHistoryRecipient = "http://127.0.0.1:5173/api/hardware-report"